# Generated by Django 4.0.1 on 2022-01-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Develop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='툴 이름')),
                ('cate', models.CharField(max_length=50, verbose_name='툴 종류')),
                ('content', models.TextField(verbose_name='개발 툴 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='아이디어 명')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='대표사진')),
                ('content', models.TextField(verbose_name='아이디어 설명')),
                ('rate', models.IntegerField(verbose_name='아이디어 관심도')),
                ('develop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWIDEA.develop')),
            ],
        ),
    ]
