# Generated by Django 4.0.1 on 2022-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('year', models.CharField(max_length=10, verbose_name='개봉년도')),
                ('genre', models.CharField(max_length=10, verbose_name='장르')),
                ('rate', models.CharField(max_length=10, verbose_name='평점')),
                ('time', models.CharField(max_length=10, verbose_name='러닝타임')),
                ('content', models.TextField(verbose_name='내용')),
                ('director', models.CharField(max_length=20, verbose_name='감독')),
                ('actor', models.CharField(max_length=20, verbose_name='배우')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
