# Generated by Django 4.0.1 on 2022-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('drama', '드라마'), ('fantasy', '판타지'), ('comedy', '코미디'), ('animation', '애니메이션')], default='action', max_length=10, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진'),
        ),
    ]
